> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.

# Common NumPy Routines Explained


## Creation & Copying

Two key concepts that must be understood when creating new arrays are:
- Memory layout: continuity or lack thereof.
- Logical layout: applies to dimensions greater than 1: the order of values in each chunk of contiguous memory.

An array's memory can either be contiguous, or discontiguous.
Contiguous memory allows for faster operations due to caching, which is something NumPy relies on to optimize.


There are two logical layouts: row-order, and column-order.
For more see: [Row and Column Order](https://en.wikipedia.org/wiki/Row-_and_column-major_order)

When using NumPy, one must be aware of there attributes, and how they are affected by various methods in the NumPy library.
This is crucial when working for example with Intel's MKL libraries, since they also specify the logical order of elements,
and memory continuity has an effect on performance.

In this section we'll introduce three terms:

convertion method: a method that convers an array-like object to a NumPy array.
creation method: a method that creates an array without receiving onother array as a parameter.
copy method: a method that creates an array in the likes of another array passed down as a parameter.

In the NumPy library, most creation methods have corresponding copy methods.
The naming convention for a copy method is the name of its creation correspondent, suffixed with `'_like'`.

The most common conversion method is `np.asarray`. (See examples below)

### The `order` Parameter

Every creation or copy method receives a key-worded argument called `order`.
This argument decides the logical and/or the memory layout of the newly created array.

This parameter can receive one of four values: `'C', 'F', 'A', 'K'`.

Both creation and copy methods may receive the following parameters:
- `'C'` - The result is a contingous array, logically arranged by row-order (also known as C-Style, or C-Continguous).
- `'F'` - The result is a contingous array, logically arranged by column-order (also known as Fortran-Style, F-Stype or F-Continguous).

The following parameters may only be passed to copy methods:
Copy methods have a parameter called `prototype` The behaviour of a copy method is affected by both the value of
`order`, and the shape,type, memory continuity of `prototype`.

- `'A'` - If `prototype` is F-Style, the result will be the same. Otherwise, the result will be C-Style (even if `prototpye` is
          not contiguous).
- `'K'` - Keep the layout of `prototype`. In this case, if `prototype` is not contiguous, so shall be the result.


### Available Routines

Creation routines:
Creation routines receive one parameter, called `shape`, and two key-worded arguments, called `order` and `dtype`.
`dtype` decides the type of elements in the result array. Its default value is float.
`shape` is an int for one-dimensional arrays, and a tuple for multi-dimensional arrays.

Common conversion routines:
* asarray

Available creation routines:
* empty: retuns an uninitialized array.
* zeros: returns an array of zeros, of the specified type.
* ones: returns an array of ones, of the the specified type.

Copy routines:
In addition to `order` and `dtype`, copy routines also receive a parameter called `a` or `prototype`.
* empty_like: creates an uninitialized array, whose shape and type match those of `prototype`.
* zeros_like: creates an array initialized with zeros, whose shape and type match those of `prototype`.
* ones_like: creates an array initialized with ones, whose shape and type match those of `prototype`.

In addition to the two key-worded arguments mentioned above, copy routines receive a kw argument called `subok`. Its default value
is True. If it's True, the new array will be a sub-class of the type of `prototype`.


### Examples

In [1]:
import numpy as np

In [24]:
np.asarray([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
# creates an uninitialized array of dimensions 2x3
np.empty((2,3))

array([[4.65459961e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [4]:
# creates a one-dimensional array, of size 5, of type float, initialized to zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
# creates a one-dimensional array, of size 3, of type float, initialized to ones.
np.ones(3)

array([1., 1., 1.])

In [5]:
# creates a one-dimensional array, of size 5, of type int, initialized to zeros.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [6]:
# creates a one-dimensional array, initialized to ones, whose shape and type match the passed parameter.
a = np.zeros(5, dtype=int)
np.ones_like(a)

array([1, 1, 1, 1, 1])

In [7]:
# creates a one-dimensional array, initialized to ones, whose shape and type match the passed parameter.
a = np.zeros(5)
np.ones_like(a)

array([1., 1., 1., 1., 1.])

## Array Manipulation

In this section we'll focus on the following common array manipulation routines:

- np.reshape
- np.split
- np.tile
- np.concatenate
- np.stack

### Reshape

The basic syntax of [np.reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape):
> numpy.reshape(a, newshape, order='C')

> a - the input array
>
> newshape - an int or tuple of ints. This parameter decides the new shape of the array.
>
> order: This parameter defines the order of reading of elements from the `a` array. This operation does not take into account
>        the memory layout of `a`. It simply decides the logical order of read operations.
>
> The return value is a new view object whenever possible. Otherwise, a copy is returned.
>
> Note: There is no guarantee of the memory layout (C- or Fortran- contiguous) of the returned array.


#### np.reshape examples

In [13]:
a = np.zeros((2,3))
np.reshape(a, 6) # flatten the array

array([0., 0., 0., 0., 0., 0.])

In [14]:
a = np.zeros((2,3))
np.reshape(a, (3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Split

The basic syntax of [np.split](https://numpy.org/doc/stable/reference/generated/numpy.split.html#numpy.split):
> numpy.split(ary, indices_or_sections, axis=0)

> ary - the array to be divided into sub-arrays.
>
> indices_or_sections - an int or a 1-D array of ints.
>                       If the value is an int, N, the array will be split into N equal arrays along `axis`.
>                       Otherwise, each cell in the array defines the end index of each sub-array.
>
> axis - the axis along which to split. Default is 0.
>
> Return value: a list of sub-arrays as views into `ary`.
>
> Error handling: An error is thrown if `indices_or_sections` is an integer, N, but `ary` cannot be divided into sub-arrays of equal sizes. In this case `ValueError` is thrown.

#### np.split examples

In [19]:
a = np.asarray([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [21]:
# split a into 2 equally sized sub-arrays.
s = np.split(a, 2)
s

[array([1, 2]), array([3, 4])]

In [23]:
s = np.split(a, [1, 3])
s # the result is a list of size three: a[:1], a[1:3], a[3:]

[array([1]), array([2, 3]), array([4])]

In [22]:
# error case
s = np.split(a, 3)
s

ValueError: array split does not result in an equal division

### Tile

The basic syntax of [np.tile](https://numpy.org/doc/stable/reference/generated/numpy.tile.html#numpy.tile):
> numpy.tile(A, reps)

> A - the input array
>
> reps - the number of repititions of A along each axis. It can be an int, or an array-like container of ints.
>        In the latter case, indices of `reps` inversly correspond to the dimension of the output array. (See examples below).
>
> Return value: a newly create tiled array.

#### np.tile examples

In [27]:
a = np.asarray([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [28]:
b = np.tile(a, 2)
b

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [32]:
b = np.tile(a, [2, 4])
b

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [31]:
b = np.tile(a, [3, 2, 4])
b

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]],

       [[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]],

       [[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]]])

### Concatenate

The basic syntax of [np.concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate):
> numpy.concatenate((a1, a2, ...), axis=0, out=None)

> (a1, a2, ...) - a sequence of array-like objects.
>
>  axis - the axis along which to concatenate the given sequence.
>
> out - an optional argument. If provided, the result will be written to the object pointed to by `out` instead of returning it.
>
> Return value: a newly created concatenated array.
>
> Error handling: an error is thrown if the axis is out of bounds, or if dimensions of the array-like objects in the given sequence mismatch


#### np.concatenate Examples

In [43]:
# normal case: concatenate along axis 0
a1 = np.asarray([[1, 2], [3, 4]])
a2 = np.asarray([[5, 6], [7, 8]])

c = np.concatenate((a1, a2))
c, c.shape

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 (4, 2))

In [44]:
# normal case: concatenate along axis 1
a1 = np.asarray([[1, 2], [3, 4]])
a2 = np.asarray([[5, 6], [7, 8]])

c = np.concatenate((a1, a2), axis=1)
c, c.shape

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 (2, 4))

In [45]:
# error case: axis out of bounds
a1 = np.asarray([[1, 2], [3, 4]])
a2 = np.asarray([[5, 6], [7, 8]])

c = np.concatenate((a1, a2), axis=2)
c, c.shape

AxisError: axis 2 is out of bounds for array of dimension 2

In [46]:
# error case: dimension mismatch
a1 = np.asarray([[1, 2], [3, 4]])
a2 = np.asarray([5, 6])

c = np.concatenate((a1, a2))
c, c.shape

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### Stack

The basic syntax of [np.stack](https://numpy.org/doc/stable/reference/generated/numpy.stack.html#numpy.stack):

> numpy.stack(arrays, axis=0, out=None)
>
> arrays - a sequence of array-like objects. All objects must have the same shape.
>
> axis - the axis in the result array along which the input arrays are stacked.
>
> out - An optional argument. If provided, the result array will be written to the memory block pointed to by `out`. Otherwise, the result is returned.

#### np.stack Examples

In [50]:
a1 = np.asarray([1, 2])
a2 = np.asarray([3, 4])

b = np.stack((a1, a2))
b

array([[1, 2],
       [3, 4]])

In [53]:
a1 = np.asarray([1, 2])
a2 = np.asarray([3, 4])

b = np.stack((a1, a2), axis=1)
b, b.shape

(array([[1, 3],
        [2, 4]]),
 (2, 2))

In [54]:
a1 = np.asarray([[1, 2], [3, 4]])
a2 = np.asarray([[5, 6], [7, 8]])

b = np.stack((a1, a2))
b, b.shape

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 (2, 2, 2))

In [55]:
a1 = np.asarray([[1, 2], [3, 4]])
a2 = np.asarray([[5, 6], [7, 8]])

b = np.stack((a1, a2), axis=1)
b, b.shape

(array([[[1, 2],
         [5, 6]],
 
        [[3, 4],
         [7, 8]]]),
 (2, 2, 2))

In [9]:
!pip install jovian --upgrade -q

You should consider upgrading via the '/opt/conda/bin/python3.7 -m pip install --upgrade pip' command.


In [10]:
import jovian

<IPython.core.display.Javascript object>

In [58]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Uploading notebook to https://jovian.ml/caesar-jeries/numpy-array-operations


<IPython.core.display.Javascript object>